// create array of cars the show in dom
export default [
  {
    id: 1,
    name: "Black Lexus",
    brand: "Lexus",
    passengers: "5",
    color: "black",
    img: require("../../images/black-car-2.jpg"),
    rating: 3.8,
    price: 650,
  },

  {
    id: 2,
    name: "White BMW",
    brand: "BMW",
    passengers: "4",
    color: "white",
    img: require("../../images/gray-car-1.jpg"),
    rating: 3.5,
    price: 785,
  },

  {
    id: 3,
    name: "Blue Nissan",
    brand: "Nissan",
    passengers: "4",
    color: "blue",
    img: require("../../images/blue-car-3.jpg"),
    rating: 4.9,
    price: 800,
  },
  {
    id: 4,
    name: "Black Tesla",
    brand: "Tesla",
    passengers: "2",
    color: "black",
    img: require("../../images/black-car-2.jpg"),
    rating: 4.5,
    price: 500,
  },
  {
    id: 5,
    name: "Gray Tesla",
    brand: "Tesla",
    passengers: 4,
    color: "gray",
    img: require("../../images/car-7.jpg"),
    rating: 3.2,
    price: 1500,
  },
  {
    id: 6,
    name: "Black Carolla",
    brand: "Carolla",
    passengers: 4,
    color: "black",
    img: require("../../images/black-car-2.jpg"),
    rating: 3.7,
    price: 900,
  },
];
